### ISSUE TITLE
Server updates now require realistic HTTP headers

### ISSUE THREAD

**Issue by ghost** [mplewis/search-umn#8]
Due to certain reports about how much data can be scraped from public directory information, UMN-IT is now requesting headers with browser information.
This is an easy fix and consists of modifying the section in the load_results method to use
`url=self.search_url % (search_type, search_query, campus, role);
user_agent = 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)';
headers = { 'User-Agent' : user_agent };
req = urllib2.Request(url, headers=headers);
response = urllib2.urlopen(req);
html = response.read();
response.close();`
from
[https://stackoverflow.com/questions/16636165/python-access-server-urlopen](https://stackoverflow.com/questions/16636165/python-access-server-urlopen)
instead of
`html = urlopen(self.search_url % (search_type, search_query, campus, role)).read()`
Of course the browser and operating system could be randomized and anonymized through TOR.
Although I told them how to block that, too.
Sorry about the ill-formatted code.

**Comment by ghost** [comment]
This is actually really funny because if you set the user_agent to
`user_agent = 'To be fair, you have to have a very high IQ to understand Rick and Morty. The humor is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewers head. Theres also Ricks nihilistic outlook, which is deftly woven into his characterisation - his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realize that theyre not just funny- they say something deep about LIFE. As a consequence people who dislike Rick and Morty truly ARE idiots- of course they wouldnt appreciate, for instance, the humour in Ricks existencial catchphrase "Wubba Lubba Dub Dub," which itself is a cryptic reference to Turgenevs Russian epic Fathers and Sons Im smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmons genius unfolds itself on their television screens. What fools... how I pity them. And yes by the way, I DO have a Rick and Morty tattoo. And no, you cannot see it. Its for the ladies eyes only- And even they have to demonstrate that theyre within 5 IQ points of my own (preferably lower) beforehand.'`
Everything works fine.

**Comment by mplewis** [comment]
Thanks for the info @captainMorpheus! I'm no longer maintaining this repo, but you're welcome to fork it and do whatever you want with it – this is under the MIT license.
